#!/usr/bin/env python3
"""gen_popular_packages.py — maintainer-run generator for dep-guard's typosquat corpus.

This is NOT a shipped gate. It lives in ``scripts/`` (outside the portability glob),
it USES THE NETWORK, and its OUTPUT — ``plugins/core-engineering/skills/ce-implement/
scripts/popular-packages.json`` plus the two forked copies — is committed, so the gate
(dep-guard.py) itself stays fully offline and deterministic. Rebuild the corpus, then
re-sync the forks:

    python3 scripts/gen_popular_packages.py --write
    python3 scripts/fork_sync.py --write

Ecosystem sources (top-N by download / popularity, fetched fresh each run; each source URL
and the fetch date are recorded in the output's ``_generated`` metadata key, which the
loader ignores):

  npm    wooorm/npm-high-impact ``lib/top-download.js`` — an array of package names in
         descending 30-day-download order (community-maintained, download-ranked).
  pypi   hugovk/top-pypi-packages ``top-pypi-packages.min.json`` — rows sorted by 30-day
         PyPI download count.
  nuget  NuGet's Azure Search query service — fetch the top 1000 candidates, then re-sort
         locally by ``totalDownloads`` (descending, id as a stable tie-break).
  cargo  crates.io API with ``sort=downloads`` — paginated 100 at a time.
  go     CURATED SEED. Go has no public download-ranked registry API: the module mirror
         (proxy.golang.org) publishes no download counts, and deps.dev exposes no
         top-N-by-popularity listing. Rather than fake a ranking, this list is a
         hand-maintained set of high-traffic Go modules — the genuine typosquat targets —
         defined in ``GO_SEED`` below and documented honestly. Extend it by hand.

Modes:
  --write        fetch every ecosystem and (re)write the canonical popular-packages.json.
                 This is the default when no mode flag is given.
  --check        fetch, then diff the ecosystem lists against the committed file; exit
                 0 (identical) / 1 (drift — re-run --write) / 2 (a fetch failed). An
                 idempotence dry-run — run it right after --write to confirm stability.
                 The volatile ``_generated`` date is intentionally excluded from the diff.
  --limit N      cap each ecosystem list at N names (default 500; the corpus stays a
                 bounded backstop, never a full registry mirror).

Stdlib only (urllib) — no third-party HTTP client, so a maintainer can regenerate from a
clean Python with nothing installed.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
TARGET = (
    REPO / "plugins" / "core-engineering" / "skills" / "ce-implement"
    / "scripts" / "popular-packages.json"
)
UA = "vg-sdlc-gen-popular-packages/1.0 (+https://github.com/; dep-guard typosquat corpus)"
DEFAULT_LIMIT = 500
ECOSYSTEMS = ("npm", "pypi", "nuget", "go", "cargo")

NPM_URL = "https://raw.githubusercontent.com/wooorm/npm-high-impact/main/lib/top-download.js"
PYPI_URL = "https://raw.githubusercontent.com/hugovk/top-pypi-packages/main/top-pypi-packages.min.json"
NUGET_URL = "https://azuresearch-usnc.nuget.org/query?q=&take=1000&prerelease=false"
CRATES_URL = "https://crates.io/api/v1/crates?page={page}&per_page=100&sort=downloads"

REVISED_COMMENT = (
    "Offline typosquat backstop for dep-guard.py — the top-N most-downloaded package "
    "names per ecosystem (npm, PyPI, NuGet, Go, Cargo), regenerated by "
    "scripts/gen_popular_packages.py (see its _generated metadata for sources + date). "
    "GENERATED, not hand-curated (Go excepted — see _generated.sources.go); a near-match "
    "is a material finding to adjudicate, not a verdict — the live registry is "
    "authoritative. A bounded top-N (<=500/ecosystem) is a deliberate BACKSTOP that "
    "covers the real typosquat targets while staying far from a full registry mirror "
    "(millions of names) — intentionally capped to hold the advisory false-positive rate "
    "low. Forked byte-identical alongside each dep-guard.py copy (check.py IDENTICAL_PAIRS)."
)

# Curated high-traffic Go modules — the typosquat targets. Go has no download-ranked API,
# so this list is maintained by hand (see the module docstring). Keep it deduplicated.
GO_SEED = [
    "github.com/gin-gonic/gin", "github.com/gorilla/mux", "github.com/gorilla/websocket",
    "github.com/stretchr/testify", "github.com/spf13/cobra", "github.com/spf13/viper",
    "github.com/spf13/pflag", "github.com/spf13/afero", "github.com/sirupsen/logrus",
    "github.com/pkg/errors", "github.com/google/uuid", "github.com/google/go-cmp",
    "github.com/google/wire", "github.com/google/go-github", "github.com/golang/protobuf",
    "google.golang.org/protobuf", "google.golang.org/grpc", "google.golang.org/api",
    "github.com/prometheus/client_golang", "github.com/prometheus/common",
    "github.com/prometheus/procfs", "github.com/prometheus/client_model",
    "github.com/labstack/echo", "github.com/labstack/echo/v4",
    "github.com/go-sql-driver/mysql", "github.com/lib/pq", "github.com/jmoiron/sqlx",
    "gorm.io/gorm", "gorm.io/driver/postgres", "gorm.io/driver/mysql",
    "github.com/mattn/go-sqlite3", "github.com/jackc/pgx", "github.com/jackc/pgx/v4",
    "github.com/jackc/pgx/v5", "github.com/redis/go-redis", "github.com/go-redis/redis",
    "github.com/go-redis/redis/v8", "github.com/gomodule/redigo",
    "go.mongodb.org/mongo-driver", "github.com/aws/aws-sdk-go",
    "github.com/aws/aws-sdk-go-v2", "github.com/hashicorp/consul",
    "github.com/hashicorp/vault", "github.com/hashicorp/go-multierror",
    "github.com/hashicorp/go-hclog", "github.com/hashicorp/hcl",
    "github.com/hashicorp/go-retryablehttp", "github.com/mitchellh/mapstructure",
    "github.com/mitchellh/go-homedir", "github.com/mitchellh/copystructure",
    "github.com/fsnotify/fsnotify", "github.com/json-iterator/go",
    "github.com/tidwall/gjson", "github.com/tidwall/sjson", "github.com/valyala/fasthttp",
    "github.com/gofiber/fiber", "github.com/gofiber/fiber/v2", "github.com/urfave/cli",
    "github.com/urfave/cli/v2", "github.com/rs/zerolog", "github.com/rs/cors",
    "github.com/rs/xid", "go.uber.org/zap", "go.uber.org/multierr", "go.uber.org/atomic",
    "go.uber.org/fx", "github.com/golang-jwt/jwt", "github.com/golang-jwt/jwt/v4",
    "github.com/golang-jwt/jwt/v5", "github.com/dgrijalva/jwt-go",
    "github.com/dgraph-io/badger", "go.etcd.io/etcd", "github.com/coreos/go-oidc",
    "golang.org/x/crypto", "golang.org/x/net", "golang.org/x/sync", "golang.org/x/sys",
    "golang.org/x/text", "golang.org/x/time", "golang.org/x/oauth2", "golang.org/x/exp",
    "golang.org/x/tools", "golang.org/x/term", "golang.org/x/mod",
    "github.com/opentracing/opentracing-go", "go.opentelemetry.io/otel",
    "go.opentelemetry.io/otel/trace", "github.com/uber/jaeger-client-go",
    "github.com/segmentio/kafka-go", "github.com/IBM/sarama", "github.com/Shopify/sarama",
    "github.com/nats-io/nats.go", "github.com/rabbitmq/amqp091-go",
    "github.com/streadway/amqp", "github.com/go-chi/chi", "github.com/go-chi/chi/v5",
    "github.com/julienschmidt/httprouter", "github.com/BurntSushi/toml",
    "gopkg.in/yaml.v2", "gopkg.in/yaml.v3", "github.com/ghodss/yaml",
    "github.com/davecgh/go-spew", "github.com/pmezard/go-difflib",
    "github.com/stretchr/objx", "github.com/cespare/xxhash", "github.com/cespare/xxhash/v2",
    "github.com/klauspost/compress", "github.com/andybalholm/brotli",
    "github.com/pierrec/lz4", "github.com/golang/snappy", "github.com/dustin/go-humanize",
    "github.com/olekukonko/tablewriter", "github.com/schollz/progressbar/v3",
    "github.com/briandowns/spinner", "github.com/fatih/color", "github.com/mgutz/ansi",
    "github.com/manifoldco/promptui", "github.com/AlecAivazis/survey/v2",
    "github.com/charmbracelet/bubbletea", "github.com/charmbracelet/lipgloss",
    "github.com/muesli/termenv", "github.com/subosito/gotenv",
    "github.com/joho/godotenv", "github.com/kelseyhightower/envconfig",
    "github.com/caarlos0/env", "github.com/go-playground/validator",
    "github.com/go-playground/validator/v10", "github.com/asaskevich/govalidator",
    "github.com/robfig/cron", "github.com/robfig/cron/v3", "github.com/patrickmn/go-cache",
    "github.com/allegro/bigcache", "github.com/coocood/freecache",
    "github.com/bradfitz/gomemcache", "github.com/elastic/go-elasticsearch",
    "github.com/olivere/elastic", "github.com/graphql-go/graphql",
    "github.com/99designs/gqlgen", "github.com/swaggo/swag",
    "github.com/swaggo/gin-swagger", "github.com/gin-contrib/cors",
    "github.com/gin-contrib/sessions", "github.com/casbin/casbin",
    "github.com/cenkalti/backoff", "github.com/cenkalti/backoff/v4",
    "github.com/avast/retry-go", "github.com/sony/gobreaker",
    "github.com/gogo/protobuf", "github.com/grpc-ecosystem/grpc-gateway",
    "github.com/grpc-ecosystem/grpc-gateway/v2",
    "github.com/grpc-ecosystem/go-grpc-middleware", "github.com/soheilhy/cmux",
    "github.com/oklog/run", "github.com/oklog/ulid", "github.com/segmentio/ksuid",
    "github.com/bwmarrin/snowflake", "github.com/bwmarrin/discordgo",
    "github.com/shopspring/decimal", "github.com/samber/lo", "github.com/pelletier/go-toml",
    "github.com/pelletier/go-toml/v2", "github.com/spf13/jwalterweatherman",
    "github.com/gofrs/uuid", "github.com/satori/go.uuid", "github.com/hashicorp/golang-lru",
    "github.com/patrickmn/go-cache", "github.com/antonmedv/expr", "github.com/tidwall/buntdb",
]


def _get_text(url: str) -> str:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as resp:
        return resp.read().decode("utf-8")


def _get_json(url: str):
    return json.loads(_get_text(url))


def _dedup(names) -> list:
    """Preserve first-seen order; drop blanks and case-insensitive duplicates."""
    seen, out = set(), []
    for n in names:
        k = (n or "").strip()
        if k and k.lower() not in seen:
            seen.add(k.lower())
            out.append(k)
    return out


def fetch_npm(limit: int) -> list:
    text = _get_text(NPM_URL)
    # `export const topDownload = [ 'semver', 'minimatch', ... ]` — quoted names, in order.
    names = re.findall(r"'([^']+)'", text)
    if not names:
        raise RuntimeError("npm source returned no names (format changed?)")
    return _dedup(names)[:limit]


def fetch_pypi(limit: int) -> list:
    data = _get_json(PYPI_URL)
    rows = data.get("rows") or []
    if not rows:
        raise RuntimeError("pypi source returned no rows (format changed?)")
    return _dedup(r["project"] for r in rows)[:limit]


def fetch_nuget(limit: int) -> list:
    data = _get_json(NUGET_URL)
    rows = data.get("data") or []
    if not rows:
        raise RuntimeError("nuget source returned no data (format changed?)")
    rows.sort(key=lambda r: (-(r.get("totalDownloads") or 0), r.get("id", "").lower()))
    return _dedup(r["id"] for r in rows)[:limit]


def fetch_cargo(limit: int) -> list:
    out: list = []
    page = 1
    while len(out) < limit and page <= 20:
        data = _get_json(CRATES_URL.format(page=page))
        crates = data.get("crates") or []
        if not crates:
            break
        out.extend(c["name"] for c in crates)
        page += 1
    if not out:
        raise RuntimeError("cargo source returned no crates (format changed?)")
    return _dedup(out)[:limit]


def fetch_go(limit: int) -> list:
    return _dedup(GO_SEED)[:limit]


FETCHERS = {
    "npm": (fetch_npm, NPM_URL, "wooorm/npm-high-impact lib/top-download.js — 30-day downloads, descending"),
    "pypi": (fetch_pypi, PYPI_URL, "hugovk/top-pypi-packages — 30-day PyPI download count"),
    "nuget": (fetch_nuget, NUGET_URL, "NuGet Azure Search query service, re-sorted by totalDownloads desc"),
    "cargo": (fetch_cargo, CRATES_URL, "crates.io API, sort=downloads (paginated)"),
    "go": (fetch_go, "(none)", "curated seed — Go has no public download-ranked registry API; hand-maintained GO_SEED"),
}


def build(limit: int) -> dict:
    """Fetch every ecosystem and assemble the corpus dict. Raises on any fetch failure."""
    lists = {eco: FETCHERS[eco][0](limit) for eco in ECOSYSTEMS}
    out = {
        "_comment": REVISED_COMMENT,
        "_generated": {
            "by": "scripts/gen_popular_packages.py",
            "utc_date": datetime.now(timezone.utc).strftime("%Y-%m-%d"),
            "per_ecosystem_limit": limit,
            "counts": {eco: len(lists[eco]) for eco in ECOSYSTEMS},
            "sources": {eco: {"url": FETCHERS[eco][1], "note": FETCHERS[eco][2]} for eco in ECOSYSTEMS},
        },
    }
    for eco in ECOSYSTEMS:
        out[eco] = lists[eco]
    return out


def cmd_write(limit: int) -> int:
    try:
        corpus = build(limit)
    except Exception as e:  # noqa: BLE001 — a maintainer tool; report and exit non-zero
        print(f"gen-popular: fetch failed — {type(e).__name__}: {e}", file=sys.stderr)
        return 2
    TARGET.write_text(json.dumps(corpus, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    counts = corpus["_generated"]["counts"]
    print(f"gen-popular: wrote {TARGET.relative_to(REPO)} — " + ", ".join(f"{e}={counts[e]}" for e in ECOSYSTEMS))
    print("  next: python3 scripts/fork_sync.py --write   (re-sync the forked copies)")
    return 0


def cmd_check(limit: int) -> int:
    try:
        fresh = build(limit)
    except Exception as e:  # noqa: BLE001
        print(f"gen-popular: fetch failed — {type(e).__name__}: {e}", file=sys.stderr)
        return 2
    try:
        committed = json.loads(TARGET.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as e:
        print(f"gen-popular: cannot read committed corpus: {e}", file=sys.stderr)
        return 2
    drifted = [eco for eco in ECOSYSTEMS if fresh.get(eco) != committed.get(eco)]
    if drifted:
        print(f"gen-popular: DRIFT — {', '.join(drifted)} differ from a fresh fetch; re-run --write.")
        return 1
    print("gen-popular: OK — the committed corpus matches a fresh fetch (ecosystem lists identical).")
    return 0


def main(argv=None) -> int:
    p = argparse.ArgumentParser(description="Regenerate dep-guard's popular-packages.json typosquat corpus (network).")
    mode = p.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true", help="fetch and (re)write the canonical corpus (default)")
    mode.add_argument("--check", action="store_true", help="fetch and diff against the committed corpus (0 same / 1 drift / 2 fetch fail)")
    p.add_argument("--limit", type=int, default=DEFAULT_LIMIT, help=f"per-ecosystem cap (default {DEFAULT_LIMIT})")
    args = p.parse_args(argv)
    limit = max(1, args.limit)
    if args.check:
        return cmd_check(limit)
    return cmd_write(limit)


if __name__ == "__main__":
    sys.exit(main())
